title: Miguel Guarniz
description: Software Engineer  
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpeg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "mi9uel9@gmail.com"
linkedin: "https://www.linkedin.com/in/mguarniz/"
github: "https://www.github.com/kckeiks"
website: "https://www.github.com/kckeiks"
medium: "https://www.github.com/kckeiks"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
